language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - npm install
  - (cd ./app && npm install)
script:
  - npm test
  - (cd ./app && npm run test)
  - docker-compose build
  - docker push

sudo: required
services:
    - docker
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

