language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - npm install
  - (cd ./app && npm install)
script:
  - npm test
  - (cd ./app && npm run test)
  - docker-compose build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"
  - docker tag linkhub_linkhub linkhub:build-$TRAVIS_BUILD_ID
  - docker push linkhub:build-$TRAVIS_BUILD_ID
sudo: required
services:
    - docker
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

