sudo: required
language: node_js
node_js:
  - "stable"
services:
  - docker

cache:
  directories:
  - node_modules

install:
#  - npm install
#  - (cd ./app && npm install)

before_script:
  - echo "Branch... $TRAVIS_BRANCH"

script:
  - echo "no tests!" # put your normal testing scripts here
#  - npm test
#  - (cd ./app && npm run test)

after_success:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY";
#  - docker build -t registry.heroku.com/linkhub-danielloeh/web .;
#  - docker push registry.heroku.com/linkhub-danielloeh/web

deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  app: linkhub-danielloeh