language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - npm install
  - (cd ./app && npm install)
before_script:
  # this install.sh script requires sudo
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
script:
  - /usr/local/heroku/bin/heroku container:login
  - /usr/local/heroku/bin/heroku container:push linkhub
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"
#  - docker-compose build
#  - docker tag linkhub_linkhub registry.heroku.com/linkhub-danielloeh/linkhub:build-$TRAVIS_BUILD_ID
#  - docker push registry.heroku.com/linkhub-danielloeh/linkhub:build-$TRAVIS_BUILD_ID
sudo: required
services:
    - docker
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

