language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
#install:
#  - npm install
#  - (cd ./app && npm install)

jobs:
  include:
    - stage: unit tests
      script:
        -"Running unit tests (1)"
      #  - npm test
      #  - (cd ./app && npm run test)
    - stage: deploy to production
      deploy:
        <<: *heroku
        app: linkhub-danielloeh
        api_key: $HEROKU_AUTH_TOKEN
      sudo: required
      before_script:
        - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      services:
        - docker
      env:
        - DOCKER_COMPOSE_VERSION=1.4.2
      script:
        - /usr/local/heroku/bin/heroku login
        - /usr/local/heroku/bin/heroku container:login
        - /usr/local/heroku/bin/heroku container:push linkhub




