version: '2'

services:
  linkhub:
      build:
        context: .
        args:
          - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
      environment:
          - EDIT_ENABLED=${EDIT_ENABLED}
      ports:
        - "8080:8080"